docs: troubleshooting
maidsafe/autonomi pull request #1315
Opened 2024-02-15 20:04 UTC by JasonPaulGithub

## Description

reviewpad:summary

2024-02-15 21:24 UTC, jacderida commented on README.md
> +### TroubleShooting
Hey, sorry for the little nitpick, but "troubleshooting" is one word, so the capital isn't necessary on the 's'.

I would suggest changing this just a little bit:
When attempting to launch a local network, if you encounter an error message similar to the following:
...

It indicates a change in the `NodeRegistry` struct, such that it is no longer compatible with a previously serialized representation.

Delete the node registry file on your platform:
C:\Users\<username>\AppData\Roaming\safe\node_registry.json
~/.local/share/safe/node_registry.json

2024-02-19 08:03 UTC, joshuef requested changes
This is way too specific. So the top changes remove `chris` are fine. 

But the throubleshooting section doesnt make sense to me.

2024-02-19 13:38 UTC, joshuef commented
can you update the commit comment to better reflect the PR now, @JasonPaulGithub ? 🙇

2024-02-19 14:12 UTC, joshuef approved these changes

2024-02-19 15:22 UTC, merged