feat(cli): files download respects filename path
maidsafe/autonomi pull request #1383
Opened 2024-03-04 00:05 UTC by iancoleman

`safe files download NAME ADDR` requires the two parameters.

The option to run `safe files download` (without name or addr) would "download all files uploaded by the current user", which (apparently) has no real world use case so is removed.

The download location is no longer $HOME/Downloads, instead using $PWD to store the file relative to where the download command is run. This can be used with both relative paths and absolute paths. This was discussed by the community in [NewYearNewNet post 405](https://safenetforum.org/t/newyearnewnet-04-01-2024-testnet-offline/39034/455).

## Description

reviewpad:summary

2024-03-04 09:13 UTC, grumbach commented on sn_cli/src/subcommands/files.rs
> +                // file_name may direct the downloaded data to:
```suggestion
            if let Some(file_name) = file_name {
                // file_name may direct the downloaded data to:
```
With this we don't need the `.expect("...")` below

2024-03-04 09:13 UTC, grumbach commented on sn_cli/src/subcommands/files.rs
> +                let file_name_val = file_name.expect("file_name unspecified");
This expect can be removed

2024-03-04 09:15 UTC, grumbach commented on sn_cli/src/subcommands/files.rs
> +                        file_name_dir.expect("file_name relative directory unspecified");
Same here, this expect could be removed with an `if let Some(file_name_dir) = file_name_dir` clause

2024-03-04 09:15 UTC, grumbach requested changes
Excellent suggestion!
Some tiny code improvement suggestions related to removable `.expect(...)` statements

2024-03-05 10:16 UTC, iancoleman commented
Thanks @grumbach  for the tips with rust style, I really appreciate learning how to improve this sort of thing.

The suggestions were implemented as of commit https://github.com/maidsafe/safe_network/commit/e86be0f459e0111e605fda22d0c1dba9b8df446e

2024-03-05 12:29 UTC, grumbach approved these changes
LGTM

2024-03-05 13:03 UTC, merged