refactor: simple counter
maidsafe/autonomi pull request #1475
Opened 2024-03-20 16:52 UTC by JasonPaulGithub

Simple counter to replace counter that threads through several functions

2024-03-20 21:39 UTC, joshuef requested changes

2024-03-20 21:39 UTC, joshuef commented on sn_cli/src/subcommands/files.rs
> +fn file_count(file_path: &PathBuf) -> u32 {
can we add some docs here please.

Ie, does this recursively count files in a dir and child folders?

2024-03-21 10:44 UTC, JasonPaulGithub commented on sn_cli/src/subcommands/files.rs
> +fn file_count(file_path: &PathBuf) -> u32 {
function renamed to count_files_in_path_recursively

2024-03-22 00:12 UTC, joshuef approved these changes

2024-03-22 02:00 UTC, merged