feat(node): carry out chunk_proof chunk against peer
maidsafe/autonomi pull request #1518
Opened 2024-03-27 13:19 UTC by maqi

## Description

reviewpad:summary

2024-03-28 21:58 UTC, JasonPaulGithub approved these changes

2024-03-28 21:58 UTC, JasonPaulGithub commented on sn_networking/src/event.rs
> +            if !keys_to_fetch.is_empty() {
write conditionals to a positive logic for better readability:

if keys_to_fetch.is_empty() 
{ trace!("no waiting keys to fetch from the network"); } 
else 
{ self.send_event(NetworkEvent::KeysToFetchForReplication(keys_to_fetch)); }

2024-03-28 21:58 UTC, JasonPaulGithub commented on sn_node/src/node.rs
> +                    if let Ok(Response::Query(QueryResponse::GetChunkExistenceProof(Ok(proof)))) =
this is not critical but be careful of statements like this turning into what's known as an "arrow head" pattern.
[This](https://medium.com/@mena.meseha/how-to-refactor-the-arrow-type-code-8c40c21db85f) article can share more on this but in short, the best way to solve this is to extract the block of if statements into their own functions

2024-03-28 21:59 UTC, JasonPaulGithub commented
comments not worth wasting time over, i have ODD tomorrow. back on Monday. Save time.
Please let me know you checked the comments @maqi

2024-03-31 22:21 UTC, joshuef requested changes, later dismissed
Some small things to help with clarity, overall looking good though!

2024-03-31 22:21 UTC, joshuef commented on sn_networking/src/event.rs
> +    fn select_verify_candiates(&mut self, peer: NetworkAddress) -> Vec<NetworkAddress> {
`select_verify_candiates` this naming is quite vague.
`select_verification_data_candidates` perhaps?

2024-03-31 22:21 UTC, joshuef commented on sn_node/src/node.rs
> +                        tokio::time::sleep(std::time::Duration::from_secs(15)).await;
can we clean this up and get the time in a documented const, please 🙇 (same with `attempts`)

2024-04-01 10:32 UTC, JasonPaulGithub approved these changes

2024-04-01 10:36 UTC, JasonPaulGithub commented
Hi @joshuef 
I see the requested changes have been resolved but the review is still marked as requested, so i'll dismiss the pending review and get this through. Hope that's ok

2024-04-01 10:38 UTC, JasonPaulGithub commented
Thanks chaps 👍

2024-04-01 11:06 UTC, merged