feat: upgrade cli audit to use DAG
maidsafe/autonomi pull request #1720
Opened 2024-05-16 21:40 UTC by grumbach

## Description

- upgrade cli audit to use DAG
- make foundation sk an optional argument in both cli and auditor as most runs won't need it (aren't related to beta rewards forwarding)

2024-05-17 11:08 UTC, maqi requested changes

2024-05-17 11:08 UTC, maqi commented on .github/workflows/memcheck.yml
> +        timeout-minutes: 15
shall not take such long time

2024-05-20 18:52 UTC, grumbach commented on .github/workflows/memcheck.yml
> +        timeout-minutes: 15
100% agree

2024-05-21 17:45 UTC, maqi approved these changes

2024-05-21 18:53 UTC, merged