feat(node): check if we have enough space before starting
maidsafe/autonomi pull request #2198
Opened 2024-10-04 21:09 UTC by RolandSherwin

- node - Check if we have enough space before starting the node
- nodemanager - check if the `(avaialable space - space reserved by other nodes)` is enough to start the `count` nodes.

2024-10-04 21:26 UTC, jacderida commented on sn_node_manager/src/cmd/node.rs
> +fn check_available_space(
Hey, I would have a suggestion here.

Perhaps you could split this function out possibly into two, and have one that passes in the nodes to operate on, without passing in the registry?

Then you could add some unit tests for the function that does the storage calculation?

I think a few test cases would probably help to understand the different cases and failures here.

2024-10-05 09:08 UTC, jacderida approved these changes

2024-10-05 11:10 UTC, maqi requested changes

2024-10-05 11:10 UTC, maqi commented on sn_node/src/bin/safenode/main.rs
> +    let required_space_bytes = (MAX_RECORDS_COUNT * *MAX_CHUNK_SIZE) as u64;
as mentioned at https://github.com/maidsafe/safe_network/commit/85c81e6c26c6ffcd50bcc5a82470ec87f9cafd21
the node_size shall be calculated as : `MAX_RECORDS_COUNT * (MAX_CHUNK_SIZE / 2)`

This calculation also appears duplicated in other place, hence better make it a helper facility

2024-10-11 12:05 UTC, RolandSherwin commented
Not required for now.

2024-10-11 16:26 UTC, RolandSherwin commented
This is currently blocked. Even our testnet machines are not spacious enough to meet the requirements. Also this can be easily bypassed, closing for now.

2024-10-11 16:26 UTC, closed without merging