fix: allow split records during crdt record puts verifications
maidsafe/autonomi pull request #2358
Opened 2024-10-30 06:21 UTC by grumbach

2024-10-30 06:38 UTC, b-zee approved these changes

2024-10-30 07:11 UTC, maqi requested changes

2024-10-30 07:11 UTC, maqi commented on sn_networking/src/lib.rs
> +                    Err(NetworkError::GetRecordError(GetRecordError::SplitRecord { .. }))
`non Wasm` build has a handling code `` trying to merge `Registers`, i.e. here get Register won't emit a SplitRecord.

not sure about Vault, but if it is a crdt type, then a merge shall be undertaken as well.

meanwhile, the `Wasm` build donesn't try to carry out `merge` yet, which could be an issue.

Swallowing an error here is also bit concerning, hence I'd suggest give it a proper handling here (if emits) or still keeps raise the error up.

2024-10-31 11:27 UTC, maqi approved these changes

2024-10-31 11:59 UTC, merged