chore: always specify the metric explicitly
maidsafe/autonomi pull request #2566
Opened 2024-12-23 11:18 UTC by RolandSherwin

2025-01-02 16:56 UTC, grumbach requested changes
Nice tweaks, but I'm not sure about the `Option` addition in the quoting metrics

2025-01-02 16:56 UTC, grumbach commented on ant-networking/src/cmd.rs
> +        sender: oneshot::Sender<Option<(QuotingMetrics, bool)>>,
Why return an option here?

2025-01-02 16:56 UTC, grumbach commented on ant-networking/src/lib.rs
> +    ) -> Result<Option<(QuotingMetrics, bool)>> {
What does None mean in this case? I think `Result<Option<_>>` is a confusing pattern

2025-01-02 16:56 UTC, grumbach commented on ant-networking/src/record_store_api.rs
> +    ) -> Option<(QuotingMetrics, bool)> {
Why do we use `Option` here?

2025-01-02 16:56 UTC, grumbach commented on ant-node/src/node.rs
> +                    }
Would getting rid of this `Option` type solve the issue of the `"This should not happen"` error here?

2025-01-09 12:56 UTC, RolandSherwin commented on ant-networking/src/cmd.rs
> +        sender: oneshot::Sender<Option<(QuotingMetrics, bool)>>,
Lemme just try to return an error instead of None type there. That makes more sense and it is cleaner

2025-01-09 14:53 UTC, grumbach commented on ant-networking/src/record_store_api.rs
> +    pub(crate) fn get_farthest(&self) -> Result<Option<RecordKey>> {
In what case do we have a `Ok(None)`?
Any chance we can simplify the return type to `Result<RecordKey>` or does the `Option` have any special meaning here?

2025-01-09 14:54 UTC, grumbach commented on ant-networking/src/record_store_api.rs
> +    pub(crate) fn get_farthest_replication_distance(&self) -> Result<Option<U256>> {
Same here

2025-01-09 14:54 UTC, grumbach approved these changes
LGTM, two questions about `Result<Option<...>>` return types

2025-01-09 14:57 UTC, RolandSherwin commented on ant-networking/src/record_store_api.rs
> +    pub(crate) fn get_farthest(&self) -> Result<Option<RecordKey>> {
It is None when the record store is empty / when the farthest record is not calculated. It is from this field.
```
    /// Farthest record to self
    farthest_record: Option<(Key, Distance)>,
```

2025-01-20 11:15 UTC, merged