fix(ci): CI should fail on DoNotMerge lable
maidsafe/autonomi pull request #695
Opened 2023-09-01 21:33 UTC by RolandSherwin

## Description

reviewpad:summary

2023-09-02 05:00 UTC, joshuef approved these changes

2023-09-02 05:05 UTC, joshuef requested changes
Hmmm, marking this as required indeed prevents merge. 

rerunning with label removed still fails though! :(

2023-09-04 07:59 UTC, RolandSherwin commented
> rerunning with label removed still fails though! :(
Hey @joshuef, I've modified it once again to run on `labeled, unlabeled, opened, synchronize, auto_merge_enabled`. 
Tried adding/removing lables, pushing new commit, force pushing, etc and it works.
It should also be run once on the merge queue, if I'm not wrong.

2023-09-04 08:46 UTC, joshuef approved these changes

2023-09-04 15:41 UTC, merged