libp2p metrics
maidsafe/autonomi pull request #705
Opened 2023-09-04 14:47 UTC by RolandSherwin

## Description

reviewpad:summary

2023-09-08 08:24 UTC, joshuef commented on sn_networking/src/event.rs
> +                            // let all_peers: Vec<_> = self.swarm.connected_peers().cloned().collect();
should this be uncommented? or removed?

2023-09-08 08:26 UTC, joshuef commented
How do we access these metrics? Do we need tostart a custom server for this? does each node run a server to access metrics?

2023-09-09 05:48 UTC, joshuef requested changes
I think `metrics` here confuses with out logging metrics output. I'd say we want a clearer name for this feature.

`libp2p-metrics`, `network-metrics` ? `something-else` ?

2023-09-09 05:48 UTC, joshuef commented
I'm also torn on this being on by default atm...

2023-09-11 06:56 UTC, RolandSherwin commented
> How do we access these metrics? Do we need tostart a custom server for this? does each node run a server to access metrics?

Yes, each node runs a separate hyper server on a random port. This returns the `OpenMetrics` response type that can be fed into grafana / other tools.

Also, I will push a change to update the feature name and remove it from the default features list.

2023-09-12 10:21 UTC, joshuef approved these changes

2023-09-12 10:55 UTC, merged