chore: output address of uploaded file
maidsafe/autonomi pull request #733
Opened 2023-09-15 21:01 UTC by jacderida

- 770a4da2 **chore: output address of uploaded file**

  Other minor adjustments for more compact text output.

- 050103b8 **feat: provide a `files ls` command**

  Gives the user to list the files they have uploaded, along with their addresses. We were storing
  this data anyway, but it's serialized to binary, so it's not human readable. A little interface on
  the client could be useful for users.

- 9759c69a **chore: clarify `files download` usage**

  The documentation for the arguments for the command are clarified, and we introduce a failure if
  only one of the name/address pair is used, as both are necessary.

  Also fix up some code from a complicated rebase.

## Description

reviewpad:summary

2023-09-18 07:11 UTC, joshuef commented
I actually think instead of https://github.com/maidsafe/safe_network/commit/050103b85320bac7a68e28395977867514b3985f we should just make that file human readable. 

`files ls` I could see having the implication it may work on any platform, but its just what you have done on this comp... (something that we will likely have later)... Feels like a plaster around just removing the bincode encoding on that file to me.

2023-09-18 07:12 UTC, joshuef requested changes
can we remove https://github.com/maidsafe/safe_network/commit/050103b85320bac7a68e28395977867514b3985f 

I'd rather we made the file human readable and that was how you can check. Doesn't feel like it needs to be in the cli to me.

2023-09-18 09:29 UTC, jacderida commented
> can we remove [050103b](https://github.com/maidsafe/safe_network/commit/050103b85320bac7a68e28395977867514b3985f)
> 
> I'd rather we made the file human readable and that was how you can check. Doesn't feel like it needs to be in the cli to me.

OK cool. Serialize to JSON?

2023-09-19 13:23 UTC, joshuef commented
> OK cool. Serialize to JSON?

Just a space separated list perhaps? (newline per file?) 


We could do json, but not sure it's worth it... treat yourself as the consumer of this (you are!) so whatever seems best!

2023-09-21 06:25 UTC, joshuef approved these changes

2023-09-21 07:06 UTC, merged