feat: publish to non-subscribed topic
maidsafe/autonomi pull request #933
Opened 2023-11-02 20:11 UTC by maqi

## Description

reviewpad:summary

2023-11-13 08:30 UTC, joshuef commented
Marking as DoNotMerge so we can assess this... 

Does it lower mem usage any? CPU? Would be good to know concretely what we get from this.

2023-11-14 10:57 UTC, joshuef commented on sn_node/src/node.rs
> +const FORWARDER_CHOOSING_FACTOR: usize = 50;
does this mean 50/50?

2023-11-14 17:40 UTC, bochaco requested changes, later dismissed

2023-11-14 17:40 UTC, bochaco commented on sn_node/tests/nodes_rewards.rs
> +    assert!(count >= 1, "Not enough notifications received");
We shouldn't relax/change this assert in our tests, we should still check we receive the exact amount of notifications thanks to deduplication implemented.

2023-11-29 12:02 UTC, joshuef approved these changes

2023-11-29 17:00 UTC, merged